name: Build and Release ESP32 Project

on:
  push:
    tags:
      - "v*.*.*"   # Trigger only on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python (needed for esptool, etc.)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Make build script executable
      - name: Make build script executable
        run: chmod +x builder/build.sh

      # 4️⃣ Run your build script
      - name: Run build script
        run: |
          echo "⚙️ Running builder/build.sh..."
          ./builder/build.sh

      # 5️⃣ Verify flasher folder exists
      - name: Verify flasher folder
        run: |
          if [ ! -d "flasher" ]; then
            echo "❌ flasher folder not found! Build script may have failed."
            exit 1
          fi
          echo "✅ flasher folder found:"
          ls -la flasher

      # 6️⃣ Zip the flasher folder
      - name: Package flasher folder
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          ZIP_NAME="Flasher-${VERSION}.zip"
          zip -r $ZIP_NAME flasher
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          echo "✅ Created ZIP: $ZIP_NAME"

      # 7️⃣ Publish ZIP as GitHub release asset
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
